### ISSUE TITLE
RepositoryCommit fails, type cast error

### ISSUE THREAD

**Issue by madisona** [DirectMyFile/github.dart#139]
Similar to #124 

```dart
import 'dart:async';
import 'package:github/server.dart';

void main() async {
  GitHub github =
      createGitHubClient(auth: new Authentication.withToken(myToken));
  RepositorySlug slug = RepositorySlug("flutter", "flutter");
  Stream<RepositoryCommit> commitResults =
      github.repositories.listCommits(slug);

  await for (RepositoryCommit commit in commitResults) {
    print(commit.commit.message);
  }
}
```

gives: 

```dart
$ ./bin/github_bug.dart 
Unhandled exception:
type 'List<dynamic>' is not a subtype of type 'List<Map<String, dynamic>>' in type cast
#0      RepositoryCommit.fromJSON (file:///Users/amadison/.pub-cache/git/github.dart-25a5e78f4cc068f9a3dd544cb2d834ecff336972/lib/src/common/model/repos_commits.dart:55:42)
#1      _MapStream._handleData (dart:async/stream_pipe.dart:227:21)
```

**Comment by tk103331** [comment]
i got the same error

![image](https://user-images.githubusercontent.com/4404609/59011781-52e18b00-8868-11e9-9343-7cd9a1e65ec6.png)
