### ISSUE TITLE
Simple example throws exception when parsing GitHub JSON response.

### ISSUE THREAD

**Issue by rmbarnett-rice** [DirectMyFile/github.dart#77]
Consider the following code:

      /* Creates a GitHub Client */
      var github = createGitHubClient();

      github.repositories.getRepository(new RepositorySlug("DirectMyFile", "github.dart")).then((Repository repo) 
      {
        print(repo.description);
      });

When executing this code the following exception is thrown:

    Uncaught Unhandled exception: 
    FormatException: Unexpected character (at line 2, character 1)
    //# sourceURL=https://api.github.com/repos/DirectMyFile/github.dart
    ^

    #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1326)
    #1      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:898)
    #2      _parseJson (dart:convert-patch/convert_patch.dart:19)
    #3      JsonDecoder.convert (dart:convert/json.dart:501)
    #4      JsonCodec.decode (dart:convert/json.dart:129)
    #5      GitHub.getJSON.<getJSON_async_body> (package:github/src/common/github.dart:251:21)
    #6      _RootZone.runUnary (dart:async/zone.dart:1137)
    ...

If I set a break point just prior to the crash, I observe this input passed to decode:

    {
        "id":22344823,"name":"github.dart","full_name":"DirectMyFile/github.dart",
        ... a lot of reasonable looking JSON ...
    }
    //# sourceURL=https://api.github.com/repos/DirectMyFile/github.dart

If I inspect the web traffic between my browser and the internet, I see the following HTTP response:

    {
        "id":22344823,"name":"github.dart","full_name":"DirectMyFile/github.dart",
        ... a lot of reasonable looking JSON ...
    }

Note the lack of the final //.

**Comment by rmbarnett-rice** [comment]
The behavior is only observed when running the code in debug mode.
